name: Run Pytest

on:
  pull_request:
    branches: ["main"]
  issue_comment: 
    types: [created]

jobs:
  test:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/test') &&
      github.event.comment.author_association == 'OWNER'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest
